---
  - name: "install nodejs."
    become: yes
    yum:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes 
      state: latest

