---
  - name: "install dependencies."
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
  
  - name: Copy backend dist files web server
    copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz

  - name: Uncompress Backend
    shell: |
      cd /home/ubuntu
      tar xvzf artifact.tar.gz -C .
      ls -la
      
  - name: Build
    become: true
    shell: |
      cd /home/ubuntu
      npm install
      npm run build

  - name: Start PM2
    shell: |
      cd /home/ubuntu
      pm2 start npm --name backend -- start

  - name: Save PM2 process list
    shell: |
      cd /home/ubuntu
      pm2 save

  - name: Startup PM2 on boot
    shell: |
      cd /home/ubuntu
      pm2 startup
      sudo env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu